site_name: "CiviCRM per a entitats del sector social dels Jesuïtes de Catalunya"
site_description: 'Aquesta documentació recull les funcionalitats pròpies de CiviCRM com també les implementades a mida i necessàries per reflectir els processos relacionats amb la gestió de les diferents entitats del sector social dels Jesuïtes de Catalunya.'
site_author: 'Francesc Bassas i Bullich'
site_url: http://docs.crm.socialsj.cat
repo_url: https://github.com/babu-cat/civicrm-for-socialsj-doc

nav:
- Introducció: 'index.md'
- CiviCRM:
    - 'Què és CiviCRM': 'civicrm/index.md'
    - 'Contactes': 'civicrm/contactes.md'
    - 'Activitats': 'civicrm/activitats.md'
    - 'Relacions': 'civicrm/relacions.md'
    - 'Grups': 'civicrm/grups.md'
    - 'Permisos': 'civicrm/permisos.md'
    - 'Contribucions': 'civicrm/contribucions.md'
    - 'Processos habituals':
        - 'Combinació de contactes': 'civicrm/processos-habituals/combinacio-contactes.md'
    - 'Preguntes més freqüents': 'civicrm/preguntes-mes-frequents.md'
    - "Annex: Llistat d'idiomes": 'civicrm/annex-idiomes.md'
- Infància:
    - 'Introducció': 'infancia/index.md'
    - 'Contactes': 'infancia/contactes.md'
    - 'Activitats': 'infancia/activitats.md'
    - 'Relacions': 'infancia/relacions.md'
    - 'Esdeveniments': 'infancia/esdeveniments.md'
    - 'Grups': 'infancia/grups.md'
    - 'Contribucions': 'infancia/contribucions.md'
    - 'Perfils': 'infancia/perfils.md'
    - 'Permisos': 'infancia/permisos.md'
    - "Guia d'ús": 'infancia/guia-us.md'
    - 'Preguntes més freqüents': 'infancia/preguntes-mes-frequents.md'
- Adults:
    - 'Introducció': 'adults/index.md'
    - 'Contactes': 'adults/contactes.md'
    - 'Activitats': 'adults/activitats.md'
    - 'Parella lingüística':
       - 'Relacions': 'adults/parella-linguistica/relacions.md'
- Atenció social:
    - 'Activitats': 'atencio-social/activitats.md'
- Voluntariat, pràctiques i educació en el lleure:
    - 'Introducció': 'voluntariat-practiques-educacio-lleure/index.md'
    - 'Voluntariat':
       - 'Introducció': 'voluntariat-practiques-educacio-lleure/voluntariat/index.md'
       - 'Contactes': 'voluntariat-practiques-educacio-lleure/voluntariat/contactes.md'
       - 'Activitats': 'voluntariat-practiques-educacio-lleure/voluntariat/activitats.md'
       - 'Relacions': 'voluntariat-practiques-educacio-lleure/voluntariat/relacions.md'
       - 'Grups': 'voluntariat-practiques-educacio-lleure/voluntariat/grups.md'
       - 'Formularis': 'voluntariat-practiques-educacio-lleure/voluntariat/formularis.md'
       - 'Informes': 'voluntariat-practiques-educacio-lleure/voluntariat/informes.md'
       - 'Esdeveniments': 'voluntariat-practiques-educacio-lleure/voluntariat/esdeveniments.md'
       - 'Plantilles de missatges': 'voluntariat-practiques-educacio-lleure/voluntariat/plantilles-de-missatges.md'
       - 'Permisos': 'voluntariat-practiques-educacio-lleure/voluntariat/permisos.md'
       - "Guia d'ús": 'voluntariat-practiques-educacio-lleure/voluntariat/guia-us.md'
    - 'Pràctiques': 'voluntariat-practiques-educacio-lleure/practiques/index.md'
    - 'Educació en el lleure': 'voluntariat-practiques-educacio-lleure/educacio-en-el-lleure/index.md'
- Esdeveniments:
    - 'Introducció': 'esdeveniments/index.md'
    - 'Preguntes més freqüents': 'esdeveniments/preguntes-mes-frequents.md'
- Comunicació:
    - 'Introducció': 'comunicacio/index.md'
    - 'Preguntes més freqüents': 'comunicacio/preguntes-mes-frequents.md'
- Captació de fons:
    - "Guia d'ús": 'captacio-de-fons/guia-us.md'
    - "Conceptes clau": 'captacio-de-fons/conceptes-clau.md'
    - "StockCrowd (EN DESENVOLUPAMENT)": 'captacio-de-fons/stockcrowd.md'
- Banc d'Aliments:
    - "Guia d'ús": 'banc-aliments/guia-us.md'
    - 'Definició': 'banc-aliments/definicio.md'
- Gent gran:
    - 'Introducció': 'gent-gran/index.md'
- CIE:
    - 'Introducció': 'cie/index.md'
    - 'Contactes': 'cie/contactes.md'
    - 'Activitats': 'cie/activitats.md'
    - 'Relacions': 'cie/relacions.md'
    - 'Grups': 'cie/grups.md'
    - 'Permisos': 'cie/permisos.md'
    - 'Perfils': 'cie/perfils.md'
- Xarxa d'Hospitalitat:
    - 'Definició': 'xarxa-hospitalitat/definicio.md'
    - "Guia d'ús": 'xarxa-hospitalitat/guia-us.md'

theme:
  name: material
  language: ca
  palette:
    primary: red
    accent: red
  icon:
    logo: fontawesome/regular/file-alt
  favicon: favicon.png

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: 'UA-117203563-1'
